CREATE TABLE [dbo].[ACHIEVEMENT]
(
	[ID] BIGINT NOT NULL IDENTITY(1, 1), 
    [TITLE] NVARCHAR(100) NOT NULL, 
    [DESCRIPTION] NVARCHAR(MAX) NULL,
	[EXPERIENCE] BIGINT NOT NULL, 
    CONSTRAINT [PK_ACHIEVEMENT] PRIMARY KEY CLUSTERED ([ID] ASC)
)
