CREATE TABLE [dbo].[AUCTION]
(
	[ID] BIGINT NOT NULL IDENTITY (1, 1), 
    [NAME] NVARCHAR(100) NOT NULL, 
	[ITEM_ID] BIGINT NOT NULL, 
    [DESCRIPTION] NVARCHAR(MAX) NULL, 
    [PRICE] BIGINT NULL, 
    [START_DATE] DATE NOT NULL, 
    [END_DATE] DATE NOT NULL, 
    CONSTRAINT [PK_AUCTION] PRIMARY KEY CLUSTERED ([ID] ASC),
	CONSTRAINT [FK_AUCTION_ITEM] FOREIGN KEY ([ITEM_ID]) REFERENCES [dbo].[ITEM] ([ID]),
)
