CREATE TABLE [dbo].[COMMENT]
(
	[ID] BIGINT NOT NULL IDENTITY(1, 1), 
    [AUTHOR_ID] BIGINT NOT NULL, 
    [RECEIVER_ID] BIGINT NOT NULL, 
    [TEXT] NVARCHAR(MAX) NULL,
	[RATING] SMALLINT NOT NULL, 
    CONSTRAINT [PK_COMMENT] PRIMARY KEY CLUSTERED ([ID] ASC),
	CONSTRAINT [FK_COMMENT_AUTHOR] FOREIGN KEY ([AUTHOR_ID]) REFERENCES [dbo].[USER] ([ID]),
	CONSTRAINT [FK_COMMENT_RECEIVER] FOREIGN KEY ([RECEIVER_ID]) REFERENCES [dbo].[USER] ([ID]),
	CONSTRAINT [CHECK_RATING] CHECK ([RATING] >= 0 AND [RATING] <= 5)
)
