CREATE TABLE [dbo].[FRIENDSHIPS]
(
	[ID] BIGINT NOT NULL IDENTITY(1, 1), 
    [USER_1_ID] BIGINT NOT NULL, 
    [USER_2_ID] BIGINT NOT NULL,
	CONSTRAINT [PK_FRIENDSHIPS] PRIMARY KEY CLUSTERED ([ID] ASC),
	CONSTRAINT [FK_FRIENDSHIPS_USER1] FOREIGN KEY ([USER_1_ID]) REFERENCES [dbo].[USER] ([ID]),
	CONSTRAINT [FK_FRIENDSHIPS_USER2] FOREIGN KEY ([USER_2_ID]) REFERENCES [dbo].[USER] ([ID])
)
