CREATE TABLE [dbo].[GAME]
(
	[ID] BIGINT NOT NULL IDENTITY (1, 1), 
    [NAME] NVARCHAR(50) NOT NULL, 
    [TYPE_ID] BIGINT NOT NULL, 
    [CATEGORY_ID] BIGINT NOT NULL, 
    [DESCRIPTION] NVARCHAR(MAX) NULL, 
    [MIN_PLAYERS] INT NULL DEFAULT 1, 
    [MAX_PLAYERS] INT NULL, 
    [PLAY_TIME] BIGINT NULL, 
	CONSTRAINT [PK_GAME] PRIMARY KEY CLUSTERED ([ID] ASC),
	CONSTRAINT [FK_GAME_TYPE] FOREIGN KEY ([TYPE_ID]) REFERENCES [dbo].[TYPE] ([ID]),
	CONSTRAINT [FK_GAME_CATEGORY] FOREIGN KEY ([CATEGORY_ID]) REFERENCES [dbo].[CATEGORY] ([ID])
)
