CREATE TABLE [dbo].[ITEM]
(
	[ID] BIGINT NOT NULL IDENTITY (1, 1), 
    [NAME] NVARCHAR(100) NOT NULL, 
	[DESCRIPTION] NVARCHAR(MAX) NULL,
	[OWNER_ID] BIGINT NOT NULL, 
    [GAME_ID] BIGINT NULL, 
    CONSTRAINT [PK_ITEM] PRIMARY KEY CLUSTERED ([ID] ASC),
	CONSTRAINT [FK_ITEM_USER] FOREIGN KEY ([OWNER_ID]) REFERENCES [dbo].[USER] ([ID]),
	CONSTRAINT [FK_ITEM_GAME] FOREIGN KEY ([GAME_ID]) REFERENCES [dbo].[GAME] ([ID])
)
