CREATE TABLE [dbo].[MEETING_ROOM]
(
	[ID] BIGINT NOT NULL IDENTITY (1, 1), 
	[ADDRESS] NVARCHAR(50) NOT NULL, 
    [DATE] DATETIME NOT NULL, 
    [MASTER_ID] BIGINT NOT NULL, 
    CONSTRAINT [PK_MEETING_ROOM] PRIMARY KEY CLUSTERED ([ID] ASC),
	CONSTRAINT [FK_MEETING_ROOM_USER] FOREIGN KEY ([MASTER_ID]) REFERENCES [dbo].[USER] ([Id])
)
