CREATE TABLE [dbo].[MEETING_ROOM]
(
	[ID] BIGINT NOT NULL IDENTITY (1, 1), 
	[ADDRESS] NVARCHAR(100) NOT NULL, 
    [DATE] TIMESTAMP NOT NULL, 
    [MASTER_ID] BIGINT NULL, 
    [GAME_ID] BIGINT NULL, 
    [CURRENT_MEMBERS] INT NOT NULL, 
    [MAX_MEMBERS] INT NOT NULL, 
    CONSTRAINT [PK_MEETING_ROOM] PRIMARY KEY CLUSTERED ([ID] ASC),
	CONSTRAINT [FK_MEETING_ROOM_USER] FOREIGN KEY ([MASTER_ID]) REFERENCES [dbo].[USER] ([ID]),
	CONSTRAINT [FK_MEETING_ROOM_GAME] FOREIGN KEY ([GAME_ID]) REFERENCES [dbo].[GAME] ([ID])
)
