CREATE TABLE [dbo].[MESSAGE]
(
	[ID] BIGINT NOT NULL IDENTITY(1, 1), 
    [SENDER_ID] BIGINT NOT NULL, 
    [RECEIVER_ID] BIGINT NOT NULL, 
    [TITLE] NVARCHAR(30) NULL, 
    [TEXT] NVARCHAR(MAX) NULL, 
	[DATE] TIMESTAMP NOT NULL, 
    CONSTRAINT [PK_MESSAGE] PRIMARY KEY CLUSTERED ([ID] ASC),
	CONSTRAINT [FK_MESSAGE_SENDER] FOREIGN KEY ([SENDER_ID]) REFERENCES [dbo].[USER] ([ID]),
	CONSTRAINT [FK_MESSAGE_RECEIVER] FOREIGN KEY ([RECEIVER_ID]) REFERENCES [dbo].[USER] ([ID])
)
