CREATE TABLE [dbo].[NEWS_TITLE]
(
	[ID] BIGINT NOT NULL IDENTITY(1, 1), 
    [TITLE] NVARCHAR(MAX) NOT NULL, 
    [TYPE] INT NOT NULL,
    [USER_ID] BIGINT NULL,
	[AUCTION_ID] BIGINT NULL,
    [MEETING_ROOM_ID] BIGINT NULL, 
    CONSTRAINT [PK_NEWS_TITLE] PRIMARY KEY CLUSTERED ([ID] ASC)
)
