CREATE TABLE [dbo].[NEWS]
(
	[ID] BIGINT NOT NULL IDENTITY(1, 1), 
	[USER_ID] BIGINT NOT NULL,
	[TYPE_OF_NEWS] INT NOT NULL,
    [TITLE_ID] BIGINT NOT NULL, 
    [DESCRIPTION_ID] BIGINT NOT NULL,
    CONSTRAINT [PK_NEWS] PRIMARY KEY CLUSTERED ([ID] ASC),
	CONSTRAINT [FK_NEWS_USER] FOREIGN KEY ([USER_ID]) REFERENCES [dbo].[USER] ([ID]),
	CONSTRAINT [FK_NEWS_NEWS_TITLE] FOREIGN KEY ([TITLE_ID]) REFERENCES [dbo].[NEWS_TITLE] ([ID])
)
