CREATE TABLE [dbo].[USERS_ACHIEVEMENTS]
(
	[ID] BIGINT NOT NULL IDENTITY(1, 1),
	[USER_ID] BIGINT NOT NULL, 
    [ACHIEVEMENT_ID] BIGINT NOT NULL, 
	CONSTRAINT [PK_USERS_ACHIEVEMENTS] PRIMARY KEY CLUSTERED ([ID] ASC),
	CONSTRAINT [FK_USERS_ACHIEVEMENTS_USER] FOREIGN KEY ([USER_ID]) REFERENCES [dbo].[USER] ([ID]),
	CONSTRAINT [FK_USERS_ACHIEVEMENTS_ACHIEVEMENT] FOREIGN KEY ([ACHIEVEMENT_ID]) REFERENCES [dbo].[ACHIEVEMENT] ([ID])
)
