CREATE TABLE [dbo].[USERS_MEETING_ROOMS]
(
	[ID] BIGINT NOT NULL IDENTITY(1, 1), 
    [MEMBER_ID] BIGINT NOT NULL, 
    [ROOM_ID] BIGINT NOT NULL,
	CONSTRAINT [PK_USERS_MEETING_ROOMS] PRIMARY KEY CLUSTERED ([ID] ASC),
	CONSTRAINT [FK_USERS_MEETING_ROOMS_USER] FOREIGN KEY ([MEMBER_ID]) REFERENCES [dbo].[USER] ([ID]),
	CONSTRAINT [FK_USERS_MEETING_ROOMS_MEETING_ROOM] FOREIGN KEY ([ROOM_ID]) REFERENCES [dbo].[MEETING_ROOM] ([ID])
)
